name: selenium pytest ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Installe Google Chrome
      - uses: browser-actions/setup-chrome@v1

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          # requirements minimal conseillé :
          # selenium
          # pytest
          # pytest-base-url
          # allure-pytest (si tu l'utilises)
          pip install -r requirements.txt

      - name: Run pytest (Chrome headless, plugin selenium désactivé)
        run: pytest -q --base-url=https://www.saucedemo.com/ -p no:selenium -rs -o sensitiveurl=
